export const routes = {
	HOME: '/home',
	LOGIN: '/login',
	REGISTER: '/register',
	DASHBOARD: '/dashboard',
	CATEGORIES: '/categories',
	PRODUCTS: '/products',
	PURCHASES: '/purchases',
	PEOPLE: '/people',
	SALE: '/sale',
	ORDERS: '/orders',
	PROFILE: '/profile',
	SETTINGS: '/settings',
	LOGOUT: '/logout',
	STAFF: '/staff',
	CUSTOMERS: '/customers',
};
